//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int SolicitudId { get; set; }
        public Nullable<int> SalasId { get; set; }
        public Nullable<int> MateriaId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFinal { get; set; }
        public string Observaciones { get; set; }
        public string Confirmacion { get; set; }
        public Nullable<byte> EstadoSolicitud { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
