//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.Materias = new HashSet<Materia>();
            this.Restablecers = new HashSet<Restablecer>();
        }
    
        public int UsuarioId { get; set; }
        public Nullable<int> RolesId { get; set; }
        public string Nombres { get; set; }
        public string Cedula { get; set; }
        public string Token { get; set; }
        public string ChatId { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<byte> Restablecer { get; set; }
        public Nullable<byte> EstadoSesion { get; set; }
        public Nullable<byte> EstadoUsuario { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materia> Materias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restablecer> Restablecers { get; set; }
        public virtual Role Role { get; set; }
    }
}
